-- CREATE DATABASE cryptoTrackerApp;

-- CREATE TABLE users (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     user_name TEXT NOT NULL UNIQUE,
--     user_email TEXT NOT NULL UNIQUE,
--     user_password TEXT NOT NULL,
--     created_at TIMESTAMP NOT NULL DEFAULT now(),
--     updated_at TIMESTAMP NOT NULL DEFAULT now()
-- );


-- CREATE TABLE user_coins (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     coins TEXT [],
--     user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
--     created_at TIMESTAMP NOT NULL DEFAULT now(),
--     updated_at TIMESTAMP NOT NULL DEFAULT now()
-- );